### ISSUE TITLE
“IS automated (New company/Flow grid)” testing

### ISSUE THREAD

**Issue by emilyvuylsteke** [Leadera/ecoman_repo#275]
I did the test with the "geneva test 2" project

I select wood as a flow and all companies. Then I click on “Begin Manual IS Process”. An error message comes out, telling me to select a sub flow (see error message in print screen). If I select the “wood” flow, all the “sub-flow” of wood should be integrated no?
![image](https://cloud.githubusercontent.com/assets/10558805/7455387/174ff238-f27c-11e4-955b-7ffe54b008cd.png)

Then, when I open the wood flow to see sub-flows, they are automatically selected. I try again to click on “calculate IS potentials”. Noting appears in the “dynamic table with IS potentials”, even though when can clearly see that there is, for example, a potential of exchange of wood between LEM and Serbeco. Therefore, I cannot go further in the testing.

Please let me know if I am misunderstanding anything. 

Thanks in advance!

**Comment by corner82** [comment]
Dear Emily,
here is my screen shot, so I can test issue, for testing purposes, please select 'test project for development'

![silinecek3](https://cloud.githubusercontent.com/assets/5053878/7455943/0c41049c-f289-11e4-836f-a87822e7c599.png)

**Comment by emilyvuylsteke** [comment]
I am sorry I don't understand. Are you asking that I use another project for testing? Where do I have to select "test project for development"?

**Comment by corner82** [comment]
Because your selection does not match any more company on your specific project, please refer my settings cause we are testing with limited data, thanks...

**Comment by emilyvuylsteke** [comment]
So the flow I've entered for the company I've created are not integrated in the dataset?

**Comment by corner82** [comment]
Hi Emily, you are totally wrong some of your assumptions, maybe I can tell you something on a hangout meeting, I think it is normal when you test an application just did not involve from the beginning...

**Comment by corner82** [comment]
Hi Emily ,
I checked database query again, query was right but 'IS sceanrio type' dropdown values made a trick,
IS scenario type value '1' should have checked all flow types but was checking for "input flow" to "input flow", so nothing was matching, I corrected drop down value, so screen shot below,

![silinecek3](https://cloud.githubusercontent.com/assets/5053878/7459540/7422f388-f2a5-11e4-98f7-bf1c2139d411.png)
Thanks for the valuable effort for this issue, we found a tricky buggu drop down value by your help, thanks anyway...

**Comment by emilyvuylsteke** [comment]
Good then :) Yes I am not sure I understood your message concerning "test project for development" but we can discuss this in the hangout meeting.

**Comment by corner82** [comment]
Did you get mey message about ''IS sceanrio type dropdown' mislead value part ?...

**Comment by emilyvuylsteke** [comment]
I still have the same problem than before concerning the flow selection (cf printscreen with message error "please select a sub-flow from flow tree").

**Comment by corner82** [comment]
You should select a subflow from tree, it is simple as that I guess....

**Comment by emilyvuylsteke** [comment]
As discussed on hangout, when selecting the group, it should automatically integrate all the subgroups. When shouldn't need to open the group and select all of them manually. Thanks in advance!

**Comment by emilyvuylsteke** [comment]
I will open a new issue for this purpose.
